#!/bin/bash
# SPDX-FileCopyrightText: 2023 Rivos Inc.
#
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

export CCACHE_DIR=/ccache

cd /workspace

rm -rf /workspace/kbuild

kernel_make () {
    make ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- 'CC=ccache riscv64-linux-gnu-gcc' 'HOSTCC=ccache gcc' O=/workspace/kbuild $@
}

user_make () {
    make ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- CC=riscv64-linux-gnu-gcc HOSTCC=gcc O=/workspace/kbuild $@
}

ccache -z

kernel_make defconfig
kernel_make kselftest-merge

# You need to build the kernel for bpf...

kernel_make -j $(($(nproc)-1))

mkdir -p /workspace/build
kernel_make INSTALL_PATH=/workspace/build install
kernel_make INSTALL_MOD_STRIP=1 \
     INSTALL_MOD_PATH=/workspace/build modules_install || true

kernel_make headers
user_make FORMAT= \
  SKIP_TARGETS="arm64 ia64 powerpc sparc64 x86 sgx" -j $(($(nproc)-1)) -C tools/testing/selftests gen_tar

# build perf
user_make -j $(($(nproc)-1)) -C tools/perf

if [[ -f /rootfs/lunar.tar ]]; then
    f=lunar.tar
elif [[ -f /rootfs/mantic.tar ]]; then
    f=mantic.tar
else
    f=sid.tar
fi

cp /rootfs/$f /workspace || true
cd /workspace/kbuild/kselftest/kselftest_install/kselftest-packages/
tar --append -f /workspace/$f ./kselftest.tar

ccache -s -vv


echo "Kernel selftest successfully built!"

